spring:
  application:
    name: secure-metrics-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/Secured-Metrics-Service/protocol/openid-connect/certs
server:
  servlet:
    context-path: /Omet
  port: 37023