spring:
  application:
    name: secure-metrics-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/secured-metrics-service/protocol/openid-connect/certs
server:
  servlet:
    context-path: /Omet
  port: 37023

client:
  keycloak:
    clientId: ${KEYCLOAK_CLIENTID}
    clientSecret:  ${KEYCLOAK_CLIENTSECRET}
    introspectionURI: ${KEYCLOAK_INTROSPECTION_URI}